---
title: "Intro GGplot"
author: "DORE Martin"
date: "2023-10-19"
output:
  rmdformats::readthedown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Librairies
```{r}
library(ggplot2)
library(gcookbook)
library(RColorBrewer)
library(paletteer)
library(MASS)
library(grid)
library(dplyr)
set.seed(10)

library(wordcloud2)
uspop10 = uspopchange[sample(nrow(uspopchange), 10),]
```

# Barplot
```{r}
plot1 = ggplot(data = uspopchange, aes(x = Abb, y = Change))+
  geom_col()
plot1
```

```{r}

uspop10 <- uspop10 %>% arrange(Change)
# Créez un vecteur de couleurs personnalisées pour chaque région
couleurs_personnalisees <- c("Red", "Blue", "Green", "Purple")

# Créez un histogramme en utilisant ggplot2 et spécifiez les couleurs
plot2 = ggplot(data = uspop10, aes(x = Abb, y = Change, fill = Region)) +
  geom_col() +
  scale_fill_manual(values = couleurs_personnalisees) +
  geom_text(aes(label = paste(Change,"%")), vjust = -0.5, color = "black")

# Affichez l'histogramme
plot2


```

# graficos de lineas


```{r}
head(tg)
```

```{r}
p = ggplot(data=tg, aes(x=dose, y = length, fill = supp, color = supp, lty = supp))+
  geom_line()+
  geom_point(shape = 21, size = 3)

p
```


```{r}
library(readr)
Temperatures <- read_csv("Temperatures.csv")
head(Temperatures)
```

```{r}
ggplot(Temperatures, aes(x = Year, y = Variation)) +
  geom_ribbon(aes(ymin = Variation - conf.level95, 
                  ymax = Variation + conf.level95), 
              alpha = 0.2) +
  geom_line()
```

```{r}
ggplot(Temperatures, aes(x = Year, y = Variation)) +
  geom_ribbon(aes(ymin = Variation - conf.level95, 
                  ymax = Variation + conf.level95), 
              alpha = 0.2,
              fill = "red") +
  geom_line()
```
```{r}
ggplot(Temperatures, aes(x = Year, y = Variation)) +
  geom_ribbon(aes(ymin = Variation - conf.level95, 
                  ymax = Variation + conf.level95),
              alpha = 0.2,
              colour = "black",
              lty = "dotted",
              size = 0.4,
              fill = "white") +
  geom_line()
```

```{r}
ggplot(Temperatures, aes(x = Year, y = Variation)) +
  geom_line() +
  geom_line(data = Temperatures,
            aes(x = Year, y = Variation - conf.level95),
            linetype = "dotted", color = "black") +
  geom_line(data = Temperatures,
            aes(x = Year, y = Variation + conf.level95),
            linetype = "dotted", color = "black") +
  scale_linetype_manual(values = c("solid", "dotted"))

```


```{r}
head(uspopage, 5)

```
```{r}
# compile les données par années
uspopage_years = aggregate(Thousands ~ Year, data = uspopage, sum)
head(uspopage_years)
```

```{r}
ggplot(data = uspopage_years, aes(x = Year, y = Thousands)) +
  geom_area(, color = "black", fill = "yellow", alpha = 0.5)
```

```{r}
ggplot(data = uspopage, aes(x = Year, y = Thousands, fill = AgeGroup))+
  geom_area(color = "black", alpha = .5)
```
```{r}
ggplot(data = uspopage, aes(x = Year, y = Thousands, fill = AgeGroup))+
  geom_area(position = "fill", color = "black", alpha = .5)+
  scale_fill_manual(values = brewer.pal(8, "Greens"))
```

# Nube de puntos
```{r}
head(heightweight)
```


```{r}
ggplot(heightweight, aes(x=ageYear, y=heightIn, shape = sex, fill= sex)) +
  geom_point(size=2.5)+
  scale_shape_manual(values = c(23,24))
```

```{r}
heightweight$weight_group = ifelse(heightweight$weightLb <= 100, "<=100", ">100")
head(heightweight)
```


```{r}
ggplot(heightweight, aes(x=ageYear, y=heightIn, shape = weight_group, fill = sex, color=sex))+
  geom_point(size=2, color = "black")+
  scale_shape_manual(values = c(23,24))+
  guides(fill = guide_legend(override.aes = c(shape=21)))
```


```{r}
ggplot(heightweight, aes(x=ageYear, y=heightIn, color = weightLb))+
  geom_point(size=2)+
  geom_rug()+
  scale_color_gradient(low = "magenta", high = "red4")
```


```{r}
ggplot(heightweight, aes(x=ageYear, y=heightIn, color = weightLb))+
  geom_point(size=2)+
  geom_rug()+
  scale_color_gradient(low = "magenta", high = "red4")+
  geom_smooth(method = "lm", se=FALSE)
```
# Histograma
```{r}
head(birthwt)
```

```{r}
ggplot(birthwt, aes(x=bwt))+
  geom_histogram(fill = "lightblue", color = "black", binwidth = 500 )+
  facet_grid(smoke~.)+
  theme_minimal()
```
```{r}
birthwt2 = birthwt
birthwt2$smoke = factor(ifelse(birthwt2$smoke == 0, "No smoke", "Smoke"))

ggplot(birthwt2, aes(x=bwt, fill = smoke))+
  geom_histogram(color = "black", binwidth = 500 )+
  facet_grid(smoke~.)+
  scale_fill_manual(values = c("lightgreen", "red2"))+
  theme_minimal()
```

```{r}
ggplot(birthwt2, aes(x=bwt, fill = smoke))+
  geom_histogram(color = "black", binwidth = 200, position = "identity", alpha = 0.6)+
  scale_fill_manual(values = brewer.pal(n=2, name="Set2"))+
  theme_minimal()
```


```{r}
ggplot(birthwt2, aes(x=bwt, fill = smoke))+
  geom_density(alpha = 0.4)+
  scale_fill_manual(values = brewer.pal(n=2, name="Set2"))+
  theme_minimal()
```

```{r}
ggplot(birthwt2, aes(x=bwt, color = smoke))+
  geom_line(stat = "density")+
  scale_color_manual(values = c("green3", "red2"))

```
```{r}
ggplot(birthwt2, aes(x=bwt, fill = smoke, color = smoke))+
  geom_histogram(aes(y = ..density..), color = "black")+
  geom_density(fill = "white", alpha = 0)+
  facet_grid(smoke~.)+
  scale_fill_manual(values = c("lightblue", "orange"))+
  scale_color_manual(values = c("blue", "red"))+
  theme_minimal()
```
```{r}
ggplot(birthwt2, aes(x=age))+
  geom_freqpoly(binwidth = 1)
```

```{r}
ggplot(birthwt2, aes(x=age))+
  geom_freqpoly(binwidth = 5, color = "blue")+
  geom_histogram(binwidth = 5, alpha = 0.5, fill = "lightblue", color = "black")
```
# boxplot
```{r}
ggplot(birthwt2, aes(x=factor(race), y = bwt, color = smoke))+
  geom_boxplot(notch = TRUE)
```

```{r}
ggplot(birthwt2, aes(x=factor(race), y = bwt, color = as.factor(race)))+
  geom_boxplot(notch = TRUE)+
  stat_summary(fun.y=mean, geom="point", shape=15, size=4, color="red") 
```

```{r}
ggplot(birthwt2, aes(x = factor(race), y = bwt))+
  geom_violin(trim = FALSE, scale = "count")
```


# Density 2D

```{r}
head(faithful)
```

```{r}
ggplot(faithful, aes(x= eruptions, y=waiting))+
  geom_point()
# stat_density_2d()
```
```{r}
ggplot(faithful, aes(x= eruptions, y=waiting))+
  geom_point()+
  stat_density_2d(aes(color=..level..))+
  scale_color_gradient(low = "blue", high = "red")
```
```{r}
ggplot(faithful, aes(x= eruptions, y=waiting))+
  geom_point()+
  stat_density_2d(aes(alpha=..density..), geom = 'raster', contour = F)
```

# Modifier les élément d'un graphique
```{r}
ggplot(faithful, aes(x= eruptions, y=waiting))+
  geom_point()+
  xlab("Eruptions") +
  ylab("Wainting")+
  ggtitle("Titulo del grafico")+
  theme(plot.title = element_text(
    color = "red",
    face = "bold"
  ),
  axis.title.x = element_text(
    color = "purple",
    size = 20
  ),
  axis.title.y = element_text(
    color = "green",
    face = "italic"
  ),
  axis.text = element_text(
    color = "yellow3"
  ))
```
```{r}
ggplot(faithful, aes(x= eruptions, y=waiting))+
  geom_point()+
  xlab("Eruptions") +
  ylab("Wainting")+
  ggtitle("Titulo del grafico")+
  geom_label(label = "grupo 1",
             x = 2,
             y = 50,
             color = "darkgreen")+
  geom_label(label = "grupo 2",
             x = 4.5,
             y = 80,
             color = "darkblue")+
  theme_classic()
```
```{r}
ggplot(birthwt2, aes(x=factor(smoke), y=bwt))+
  geom_boxplot()+
  stat_summary(fun = "mean",
               geom = "point",
               size = 3,
               color = "green3",
               shape = 15)+
  annotate(geom = "text",
           x = 1.5,
           y = 3000,
           size = 7,
           label = expression(frac(sum(x),n)),
           color = "green3")
```


```{r}
datos = climate %>% 
  filter(Source == "Berkeley")

ggplot(datos, aes(x=Year, y = Anomaly10y))+
  geom_line()+
  annotate("Segment",
           x = 1835, y = -0.9,
           xend = 1815, yend = -1,
           arrow = arrow(),
           color = "red")+
  annotate("segment",
           x = 1950, xend = 2000,
           y = -0.5, yend =-0.5,
           arrow = arrow(ends = "both"),
           color = "blue")
  
```

# WordCloud

```{r}
head(demoFreq)
```

```{r}
wordcloud2(data = demoFreq, size = 1.6)
```


```{r}
wordcloud2(data = demoFreq, size = 1.6,
           color = paletteer_d("tvthemes::Day"),
           backgroundColor = "lightyellow")
```



```{r}
wordcloud2(data = demoFreq,
           figPath = "apple.png")


# The shape of the "cloud" to draw. Can be a keyword present. Available presents are 'circle' (default), 'cardioid' (apple or heart shape curve, the most known polar equation), 'diamond' (alias of square), 'triangle-forward', 'triangle', 'pentagon', and 'star'.
```


