---
title: "Graficos Basicos"
author: "DORE Martin"
date: "2023-10-10"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Importacion de datos

```{r}
library(readr)
library(dplyr)
data_1 <- read_delim("data_1.csv", delim = ";", 
                     escape_double = FALSE, trim_ws = TRUE)
names(data_1) = c("Red_Social", "Freq_Abs", "Freq_Rel")
```


# Diagrama de barras

```{r}
library(RColorBrewer)

barplot(data_1$Freq_Abs,
        names.arg = data_1$Red_Social,
        xlim = c(0, 20),
        main = "Frecuencia de uso de las redes sociales",
        col = brewer.pal(5, "Blues"),
        xlab = "Redes sociales preferidas",
        ylab = "Frequencias",
        cex.axis = 0.5,
        cex.names = 0.5,
        cex.lab = 1.2,
        width = 0.5,
        space = 0.5,
        border = "white",
        horiz = TRUE)


percentages <- round((data_1$Freq_Abs / sum(data_1$Freq_Abs)) * 100, 1)
text(x = data_1$Freq_Abs + 1,
     y = 1 : length(data_1$Red_Social) * 0.75, 
     labels = paste(percentages, "%"),
     pos = 1)

legend("topright", legend = "leyenda", )
```


```{r}
data_2 <- read_delim("data_2.csv", delim = ";", 
    escape_double = FALSE, trim_ws = TRUE)

par(mfrow = c(1,2))
barplot(data_1$Freq_Abs,
        xlab = "Jovenes",
        main = "Frecuencia de uso de las redes sociales",
        col =rainbow(5),
        border = "white")

legend("topright", legend = data_1$Red_Social, col = rainbow(5), pch = 15)

barplot(data_2$Frecuencia_absoluta,
        xlab = "Majores de 50",
        ylab = NULL,
        col = rainbow(5),
        border = "white")


```
```{r}
data_combined = data_1 %>% left_join(data_2) %>% select(-Freq_Rel)
names(data_combined) = c("Red_Social", "Jovenes", "Majores_50")

heigths = as.matrix(data_combined[,-1])
barplot(heigths,
        col = rainbow(5))
legend("top", data_combined$Red_Social, col = rainbow(5))
```


```{r}
pie(data_1$Freq_Abs,
    labels = paste(data_1$Freq_Rel *100 , "%"),
    col = brewer.pal(5, "Set2"),
    border = "grey", 
    main = "Redes Sociales Preferidas",
    edges = 20) 
legend("topleft", data_1$Red_Social, fill = brewer.pal(5, "Set2"))
```
```{r}
library(plotrix)
pie3D(data_1$Freq_Abs, labels = data_1$Red_Social, explode= 0.10)
```

# 7

```{r}
data_covid <- read_csv("casos_hosp_uci_def_sexo_edad_provres.csv")
str(data_covid)
```


```{r}
data_covid_date = data_covid %>% 
  filter(fecha >= "2020/12/24" & fecha <= "2021/01/21") %>% 
  filter(provincia_iso=="AL")

jovenes = data_covid_date %>% 
  filter(grupo_edad == "20-29")

mayores60 = data_covid_date %>% 
  filter(grupo_edad == "60-69")

hospJoven = jovenes$num_hosp[which(jovenes$sexo == "M")] + jovenes$num_hosp[which(jovenes$sexo == "H")]
hospMayor = mayores60$num_hosp[which(mayores60$sexo == "M")] + mayores60$num_hosp[which(mayores60$sexo == "H")]
```


```{r}
hist(hospMayor, col=  "yellow", ylim=c(0,25))
hist(hospJoven, add= T, col = "pink")
```

```{r}
# plot(c(1:39), mayores60$num_hosp[which(mayores60$sexo=="M")], col="white", xlab = "", ylab = "")
```



# 6) 

