---
title: "Grafico de redes"
author: "DORE Martin"
date: "2023-12-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Librerias

```{r}
library(igraph)
```


```{r}
Nodo_1 = graph(c(1,2, 2,3, 2,4, 1,4, 5,5, 3,6))
plot(Nodo_1)
```

```{r}
Nodo_2 = graph(c(1,2, 2,3, 2,4, 1,4, 5,5, 3,6),directed=FALSE)
plot(Nodo_2, , vertex.label=NA)
```

# Ejercicio 1

```{r}
set.seed(5)
datos = matrix(sample(0:1, 100, replace=TRUE, prob=c(0.8,0.2)), nc=10)
datos
```

```{r}
nodos =  graph_from_adjacency_matrix(datos , mode='undirected', diag=F )
plot(nodos)
```

```{r}
set.seed(5)
nodos <- graph_from_adjacency_matrix(datos, mode='undirected', diag=FALSE)

E(nodos)$color <- "pink"
E(nodos)$lty <- 2
E(nodos)$width = 2 
E(nodos)$curved = .2


V(nodos)$label <- LETTERS[1:vcount(nodos)]
V(nodos)$shape = rep(c("square", "circle"),5)
V(nodos)$color <- "red"
V(nodos)$frame.color <- "green"  
V(nodos)$fill.color <- "red"  
V(nodos)$size = c(15:24)


plot(nodos)

```

2ème méthode moins bourrin

```{r}
set.seed(5)
datos <- matrix(sample(0:1, 100, replace=TRUE, prob=c(0.8,0.2)), nc=10)
nodos <- graph_from_adjacency_matrix(datos , mode='undirected', diag=F )
plot(nodos, 
     vertex.label=LETTERS[1:10], # Character vector
     vertex.label.color="orange",
     vertex.label.family="Times",
     vertex.label.font=2,
     vertex.label.cex=1,
     vertex.label.dist=-0.5, # Distance between the label and the vertex
     vertex.label.degree=0.5, # Position of the label in relation to the vertex (use pi)
     
     vertex.color="red", # Node color
     vertex.frame.color="green",  # Node border color
     vertex.shape=c("circle","square"), # none, circle, square, csquare, rectangle, crecrangle, pie, ...
     vertex.size=c(15:24), # default = 15

     edge.color="pink", 
     edge.width=2,
     edge.arrow.size=1,
     edge.arrow.width=2,
     edge.lty="dotted", 
     edge.curved=0.3) # False = 0, True = 0.5
```


# Ejercicio 2


```{r}
nodes = data.frame(
  id = c("Origen", "A", "B", "C", "D", "E", "F", "Destino"),
  label = c("Origen", "PtoA", "PtoB", "PtoC", "PtoD", "PtoE", "PtoF", "Destino"),
  workers = c(3,2,5,4,9,8,6,1),
  mandatory = c(T,T,F,F,T,F,F,T)
)

edges = data.frame(
  from = c("Origen","Origen", "A", "A", "B", "C", "D","E", "F","A","D"),
  to = c("A","B", "C", "D", "D", "E","F","Destino","Destino","Destino","Destino"),
  times = c(2,5,6,4,3,2,4,5,1,10,2)
)

graph = graph_from_data_frame(d=edges, vertices = nodes, directed = T)

layout <- matrix(c(0,1 ,2,2, 2,0, 4,2, 4,0, 6,2, 6,0, 8,1), ncol = 2, byrow = TRUE)
node_shapes <- ifelse(nodes$mandatory, "circle", "square")
node_color = ifelse(nodes$mandatory, "pink", "lightblue")

plot(graph,
     layout = layout,
     asp = .5,
     
     # Noeuds
     vertex.label.dist = 0.5,
     vertex.label.cex = 0.8,
     vertex.size = 2*nodes$workers,
     vertex.shape = node_shapes,
     vertex.color = node_color,
     vertex.frame.color = "pink",
     vertex.label.color = "red",
     
     # Arcs
     edge.label = edges$times,
     edge.label.color = "purple",
     edge.color = "green",
     edge.lty = 2,
     edge.arrow.size = 1,
     edge.width = 2
     )

title(main = "Grafico de Redes", sub = "Ruta optimal",
      col.main = "purple", col.sub = "blue", font.main = 4)
legend("bottomright", legend = c("Opcional", "Obligada"),col = c("lightblue", "pink"), lty = 1, lwd = 3, title = "Parada", bty = "n")
```

